
-- 주민
DROP TABLE IF EXISTS PERSON RESTRICT;

-- 커뮤니티
DROP TABLE IF EXISTS COMMUNITY RESTRICT;

-- 멤버십
DROP TABLE IF EXISTS MEMBERSHIP RESTRICT;

-- 클럽
DROP TABLE IF EXISTS CLUB RESTRICT;

-- 클럽카테고리
DROP TABLE IF EXISTS CLUB_CTGR RESTRICT;

-- 주민
CREATE TABLE PERSON (
	EMAIL      VARCHAR(40) PRIMARY KEY,
	NAME       VARCHAR(50) NOT NULL,
	PASSWORD   VARCHAR(20) NOT NULL,
	BIRTH_DATE DATE        NULL,
	GENDER     CHAR(1)     NULL
);

-- 커뮤니티
CREATE TABLE COMMUNITY (
	COMM_ID   INTEGER       PRIMARY KEY AUTO_INCREMENT,
	COMM_NM   VARCHAR(100)  NOT NULL,
	COMM_DESC VARCHAR(1000) NOT NULL,
	OPEN_DT   DATETIME      NOT NULL,
);

-- 멤버십
CREATE TABLE MEMBERSHIP (
	GRP_CLS   CHAR(2)     NOT NULL,
	GRP_ID    INTEGER     NOT NULL,
	EMAIL     VARCHAR(40) NOT NULL,
	MBS_ROLE  CHAR(2)     NOT NULL,
	MBS_STATE CHAR(2)     NOT NULL,
	START_DT  DATETIME    NOT NULL,
	END_DT    DATETIME    NOT NULL
);

ALTER TABLE MEMBERSHIP
	ADD CONSTRAINT PK_MEMBERSHIP -- 멤버십 기본키
		PRIMARY KEY (
			GRP_CLS, -- 그룹구분
			GRP_ID,  -- 그룹ID
			EMAIL    -- 주민이메일
		);

-- 클럽
CREATE TABLE CLUB (
	CLUB_ID    INTEGER       PRIMARY KEY AUTO_INCREMENT,
	CLUB_NM    VARCHAR(100)  NOT NULL,
	CLUB_DESC  VARCHAR(1000) NOT NULL,
	OPEN_DT    DATETIME      NOT NULL,
	CLUB_STATE CHAR(2)       NOT NULL,
	COMM_ID    INTEGER       NOT NULL,
	CTGR_NO    INTEGER       NOT NULL
);

-- 클럽카테고리
CREATE TABLE CLUB_CTGR (
	COMM_ID INTEGER            NOT NULL,
	CTGR_NO INTEGER            NOT NULL,
	CTGR_NM VARCHAR(10)        NOT NULL
);

-- 클럽카테고리
ALTER TABLE CLUB_CTGR
	ADD CONSTRAINT PK_CLUB_CTGR -- 클럽카테고리 기본키
		PRIMARY KEY (
			COMM_ID, -- 커뮤니티ID
			CTGR_NO  -- 카테고리번호
		);
